---
title: "BIOST 578 Homework 3"
author: "Yatong Li"
date: "March 2, 2015"
output: html_document
---

## Load the packages needed

```{r}
source("http://bioconductor.org/biocLite.R")
biocLite(c("GEOquery", "limma"))
library(GEOquery)
library(limma)
library(pheatmap)
```

## Download gds file

```{r}
gds.file <- getGEO("GSE40812", destdir="/Users/Yatong/Documents/Biostat-578-homework/HW3_yatong_li")
gds <- gds.file[[1]]
```

## Clean data

```{r}
pData.gds <- pData(gds)
# use a subset of the original file
pData.gds.sub <- pData.gds[ , c("title", "characteristics_ch1", "characteristics_ch1.1", "characteristics_ch1.2")]
names(pData.gds.sub) <- c("ptid", "y.status", "cell.type", "treatment")

pData.gds.sub.backup <- pData.gds.sub # make a copy of pData.gds.sub
length(pData.gds.sub$ptid) # 80

# clean-up ptid
pData.gds.sub.ptid <- vector(, 80)
for (i in 1:80) {
  temp <- pData.gds.sub.backup$ptid[i]
  pData.gds.sub.ptid[i] <- unlist(strsplit(as.character(temp), "_"))[2]
}
pData.gds.sub$ptid <- pData.gds.sub.ptid

# clean-up y.status
pData.gds.sub.y.status <- vector(, 80)
for (i in 1:80) {
  temp <- pData.gds.sub.backup$y.status[i]
  pData.gds.sub.y.status[i] <- unlist(strsplit(as.character(temp), ": "))[2]
}
pData.gds.sub$y.status <- pData.gds.sub.y.status

# clean-up cell.type
pData.gds.sub.cell.type <- vector(, 80)
for (i in 1:80) {
  temp <- pData.gds.sub.backup$cell.type[i]
  pData.gds.sub.cell.type[i] <- unlist(strsplit(as.character(temp), ": "))[2]
}
pData.gds.sub$cell.type <- pData.gds.sub.cell.type

# clean-up treatment
pData.gds.sub.treatment <- vector(, 80)
for (i in 1:80) {
  temp <- pData.gds.sub.backup$treatment[i]
  pData.gds.sub.treatment[i] <- unlist(strsplit(as.character(temp), ": "))[2]
}
pData.gds.sub$treatment <- pData.gds.sub.treatment

# check
head(pData.gds.sub)
```

## Get Microphage data
```{r}
macro.data <-gds[, pData.gds.sub$cell.type=="Monocyte-derived Macrophage"]
dim(macro.data)
head(pData(macro.data))
```

## Differential gene expression with Limma
```{r}
mm.1 <- model.matrix(~treatment + ptid, macro.data) # design matrix
fit.1 <- lmFit(macro.data, mm.1)
ebay.1 <- eBayes(fit.1)
topTable.1 <- topTable(ebay.1, coef="treatmentpoly ic h", number=Inf, sort.by="none")
# DEG <- which(topTable.1$adj.P.Val<0.05 & abs(topTable.1$logFC)>log2(1.5))
# length(DEG)
```

## Differential gene expression on a subset of probes
```{r}
Probe.id <- topTable.1$Probe_Id
Probe.id.macro.data <- rownames(exprs(macro.data))
sub.macro.data <- macro.data[Probe.id.macro.data %in% Probe.id,]

# limma
mm.2 <- model.matrix(~infection.status, sub.macro.data)
fit.2 <- lmFit(sub.macro.data, mm.2)
ebay.2 <- eBayes(fit.2)
topTable.2 <- topTable(ebay.2,number=Inf,sort.by="none")
sub.DEG <- which(top.test$P.Value < 0.1)
length(sub.DEG)
```

## Create heatmap
```{r}
# subset expression data using probes from the above ("sub.DEG")
sub.Probe.id <- topTable.2$Probe_Id[sub.DEG]
index <- Probe.id.macro.data %in% sub.Probe.id
express.macro.data <- exprs(macro.data)
sub.Probe.id.exprs.data <- express.macro.data[index, ]

# plot
pheatmap(sub.Probe.id.exprs.data)
heatmap(sub.Probe.id.exprs.data)
# 
```